"""add_session_expires_at

Revision ID: 2bb3fd613193
Revises: f484264e05f0
Create Date: 2026-08-13 16:44:19.221247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb3fd613193'
down_revision: Union[str, Sequence[str], None] = 'f484264e05f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chat_session_expires_at'), 'chat_session', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_session_expires_at'), table_name='chat_session')
    op.drop_column('chat_session', 'expires_at')
    # ### end Alembic commands ###
