"""unique_customer_name_phone

Revision ID: f484264e05f0
Revises: 4cdc33bcb945
Create Date: 2026-08-12 11:10:06.786645

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f484264e05f0'
down_revision: Union[str, Sequence[str], None] = '4cdc33bcb945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_customer_first_last_phone', 'customer', ['first_name', 'last_name', 'phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customer_first_last_phone', 'customer', type_='unique')
    # ### end Alembic commands ###
